export default {
  defaultErrorMessage: '出错啦～！请稍后重试或联系管理员',
  400: '请求参数错误',
  401: '登录已失效',
  403: '无访问权限',
  404: '请求的资源不存在，可能已被删除或参数错误',
  409: '资源冲突，数据已存在',
  429: '请求超出上限',
  500: '服务器出现错误，请稍后重试或联系管理员',
  502: '无法连接服务器，请稍后重试或联系管理员',
  'User account is locked': '账户已锁定',
  'User account is disabled': '账户已禁用',
  'User account has expired': '账户已过期',
  badCredential: '帐号或密码错误',
  badSmsCode: '短信验证码错误',
  noPermissionToOperate: '无权限访问或操作数据',
  userNotFound: '用户不存在',
  afsValidateFailed: '智能验证失败，请稍后重试',
  sessionExpired: '会话超时，请重新登陆',
  duplicatedUser: '用户已存在',
  duplicatedOperation: '当日运营信息已存在',
  captchaFailed: '验证码错误或页面已过期',
}
